# Generated by Django 4.2.7 on 2023-12-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlaylistService', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at', '-updated_at'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['-created_at'], 'verbose_name': 'Playlist', 'verbose_name_plural': 'Playlists'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['title'], 'verbose_name': 'Song', 'verbose_name_plural': 'Songs'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AddField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
        ),
        migrations.AlterModelTable(
            name='comment',
            table='custom_comment_table',
        ),
        migrations.AlterModelTable(
            name='playlist',
            table='custom_playlist_table',
        ),
    ]
