# Generated by Django 4.2.7 on 2023-12-04 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlaylistService', '0002_alter_comment_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='playlist',
            table='Playlist_table',
        ),
    ]
