# Generated by Django 4.2.7 on 2023-12-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlaylistService', '0003_alter_playlist_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='playlist',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
