# Generated by Django 4.2.7 on 2023-12-05 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlaylistService', '0004_rename_name_playlist_title_playlist_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='song',
            name='genres',
        ),
        migrations.AlterModelTable(
            name='playlist',
            table='playlist_table',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
